### ISSUE TITLE
Required small enhancements for real usability

### ISSUE THREAD

**Issue by Mathieu-Lenaers** [michd/mcdesign#9]
Hi,

First, nice try for an app but di.fm is way better...sorry, I really like DI.fm and just realised you are one of the people behind it. Had to mention that :roll_eyes:

Your MCD application is very simple to use and I appreciate K.I.S.S. designs. Unfortunately, it misses, in my opinion, two major features that should not be that complicated to add. I would do it but as it is ruby code, I am not sure I could as it is a language I am not familiar with.

The first one of these would be a layer system, to be able to effectively use this tool for blueprint designing. In the current version, and it is not only my opinion as I saw it written by a few others that tested your app, it is mainly unusable because of this.

The second one would be to add some blocks. The current ones are not sufficient to design anything as it misses many types of textures such as fences and...well...everything, in fact :disappointed_relieved: 

Hope you have at least the time to answer this, even maybe only for guiding me to contibute myself to this application. As a developer, I should be able to help if being not alone on it, especially for the deployment part and ruby wich I am not familiar with, as said above. If I find the time, I might fork & pull it locally to try to improve it a bit myself then push it back to my own Github account for you to review and merge, if my coding suits you of course :wink: 

With all my kindness,
Mat

P.S.: no, hadn't read the readme part where you say you don't touch this code anymore...but I think I'll try asking anyway :)

**Comment by michd** [comment]
Hi Mat!

Hah, I don't think the di.fm comparison is particularly fair as mcdesign is tiny side project essentially thrown together in a weekend in 2011, while working on di.fm is my actual day job. :smile:

MCDesign would definitely benefit from all the things you mentioned, and, to be frank, a rewrite.

For what it's worth, the ruby side of things only really deals with storing JSON created by the JavaScript frontend and saving it with an ID. So technically, this application can be improved a lot without knowing any ruby, if you want to just develop the frontend features and JSON generation.

The trickier part would be ensuring it remains backward compatible. After all, the old JSON stored in the database should still be parseable by an updated frontend; particularly relevant for the layers update you proposed.

Adding blocks would require that the existing ones remain mapped to the same numbers, again for backwards compatibility. Beyond those restraints, I suppose anything's possible. :)

---

I'd be happy to review / test / merge anything you come up with, but ~~can't~~ _don't want to (if I'm being honest)_ really dedicate my spare time developing this at this point... plenty of other side projects going on. :)

**Comment by Mathieu-Lenaers** [comment]
No, it ain't fair at all :laughing: It was just to mention it since I like and use it much :wink:

First, thanks for the quick answer. Wasn't expecting it so soon :smiley: 

I realised, reading a bit the code, that ruby is effectively only there for DB storage. Since I know quite well JQuery, I might be able to dig into this, having a bit of time at the moment (thus playing MC a lot :roll_eyes: ).

Concerning the backwards compatibility, I might have an idea quite simple for it to work: create a field in the json matrix mentioning the app version and parsing the old way if that field does not exist. That way, the old json will still be parseable while giving the possibility to change the matrix to include a third dimension for layers. Maybe even just a test to check if matrix has 2 or 3 dimensions should work even better, especially as this makes less data in it.

This would also allow to keep the old jpg for retrocomp and replacing this one big jpg file system by a bunch of small ones (or even taking the ones in MC files, directly, if possible according to MC copyright. This could avoid having this jpg loaded multiple times as I believe it is at the moment. I see in code that each block loads the full jpg at the right position using CSS wich might, for big designs and especially if adding a layer system, uselessly overload browser memory.

I'd like to keep it as simply stupid as it is now. Less complexity means more useability and less compatibility and maintenance problems.

---

I quite undersand you not willing to update this app (while you seem to maintain it wich is nice) as it can be quite time consuming and addictive, especially if it makes you go playing MC again :roll_eyes:

**Comment by michd** [comment]
Re: backwards compat:

Adding a version field seems like perfectly reasonable approach; no objections.

Another way I can see it work without having to keep the frontend aware of all the possible different versions, is by making a new named field called `L` or something (for layers) instead of the `m` currently for "matrix" (I guess that's what it was short for). Then the frontend can check whether there's a matrix directly in the root of the json object, or whether we're dealing with layers, and act accordingly based on that.

Concerning the single image file: This is called a spritesheet, and the aim of it is actually the opposite: it means the browser only has to make a single HTTP request to get the imagery for all textures, instead of a new one for every one that's used. The browser sees that a tile has the same background image url, and will just use the resource it has already loaded on that page again.

In the age of http 2 that may be less relevant though, as it can keep the connection open while multiple requests are made, in turn making it simpler to add more textures (not having to edit the spritesheet).

**Comment by Mathieu-Lenaers** [comment]
Regarding backwards compatibility I'll think about it but will probably go for a version field. This should make future changes, if ever any, easier to implement while keeping compatibility in the long run.

Spritesheets...I forgot the term. The two methods have benefits but all comes at a cost. According to my little research done now (https://www.google.com/search?client=firefox-b-e&q=spritesheet+or+individual+image), this quite little project would not be substancialy impacted by any of both choices except maybe for the importation and drawing of VERY large designs (like a 100x100 grid and more) wich is unlikely to happen and would not be practical to use without a zooming and movement mechanism (horizontal scroll is not practical in a browser).

At the moment, I was able to load a 100x100 grid but it takes like 10s to generate and near the same to refill with a new texture. I might start by limiting grid size to an acceptable maximum. A grid of 1Kx1K, for instance, does not load at all so no need to allow it. Cap at a hundred seems a maximum for me at the moment and stays within the width of the page without horizontal scroll.

It is very unlikely that MC players have a poor internet connection so bandwidth, if used only at design load and update, is no problem. Memory, on the other hand, is quite limited when playing while having a few browser tabs opened. I believe the best would be to go for memory and GPU usage optimisation so the game is less impacted while implementing a design.

I don't like this thread being about everything and nothing at the same time so I think you can close this issue, it seems resolved for me. I will now fork/pull the code and (try to) start a projet (I love PM) on my github account to better organise the various features to improve/implement. Do you have any recommandations and habits regarding PM? Branches/code organisation? Coding guidelines? Things you really do not want me to do appart from breaking backwards compat?

BTW, no, I will not code it in Brainfuck, even if you have a project of debugger XD

**Comment by michd** [comment]
For branching, I generally like a branch per feature; try and split ideas up into the smallest useful standalone thing, essentially.

But anyway, all I can say is have fun! :)

**Comment by Mathieu-Lenaers** [comment]
Ok, feature branches it will be, then. I'll try to do a correct and unsplitable WBS :smiley: I'm already swimming back into my old PM classes to recall what to absolutely do for an agile management.

As for the fun, I already have some :laughing:
